name: development-coop-mock

on:
  push:
    branches: [ "development/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
    # Multi-platform build need to setup QEMU and Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{secrets.DOCKER_HUB_USERNAME}}/coop-mock
        tags: |
          type=raw,value=development
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        build-args: |
          DATABASE_URL=${{secrets.DATABASE_URL}}
      
