name: development-coop-mock

on:
  push:
    branches: [ "development/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Docker image
      run: | 
        docker build -t coop-mock . \
          --build-arg DATABASE_URL="$ {{ secrets.DATABASE_URL }}"
