name: development-coop-mock

on:
  push:
    branches: [ "development/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    env: 
      DOCKER_HUB_USERNAME: $ {{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: $ {{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Docker image
      run: | 
        docker build -t "$ {{ env.DOCKER_HUB_USERNAME }}/coop-mock:development" . \
          --build-arg DATABASE_URL="$ {{ secrets.DATABASE_URL }}"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: $ {{ env.DOCKER_HUB_USERNAME }}
        password: $ {{ env.DOCKER_HUB_PASSWORD }}
    - name: Push Docker image
      run: docker push $ {{ env.DOCKER_HUB_USERNAME }}/coop-mock:development
